# Generated by Django 5.2 on 2025-05-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEATURED', 'À la une'), ('EDITORIAL', 'Éditorial'), ('SANS', 'Sans')], default='SANS', max_length=10)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='blog.post')),
            ],
            options={
                'verbose_name': "Placement en page d'accueil",
                'verbose_name_plural': "Placements en page d'accueil",
            },
        ),
    ]
